# -*- coding: utf-8 -*-
"""Numpy -data analyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1003__5q-dEWPTTKKSxdrmRnhqT2oHRDD
"""



"""NumPy - Numerical python for data analyst."""

!pip install numpy   #pip - python installing package

import numpy as np  # as - alias

arr = np.array([1,2,3,4,5,6])

arr

arr1 = np.array([[1,2,3],[4,5,6]])

arr1

arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

arr2

"""Arrary Propertis

print(arr.ndim)- dimensional,  
print(arr.shape)- shape ,  
print(arr.size)-size,  
print(arr.dtype)-data type.
"""

arr3 = np.array ([[[1,2,3,4]]])

arr3

arr.ndim  #numpy properties -arr.ndim

arr1.ndim  #numpy properties -arr1.ndim

arr2.ndim   #numpy properties -arr2.ndim

arr3.ndim  #numpy properties -arr3.ndim

arr2.shape

arr3.shape

np.shape(arr2)  #collable properties

np.shape(arr3)

arr2.size

arr3.size

arr3.dtype



"""array slicing - indexing"""

arr

arr[2]

arr[2:5]

arr[:4]

arr1

arr1[1,0]  #1st row , oth coloum

arr1[1,1]

arr1[1,2]



"""Arithmatic operations


"""

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

arr1 + arr2

arr1 + 10



"""Advanced Operations"""

arr

arr.sum()

arr.mean()

arr.max()

arr.min()

arr.std()

np.median(arr1)

arr

arr.T



"""Special functions

"""

zeros = np.zeros((2,3))

zeros

np.zeros(5)

np.ones((2,3))

np.full(5,7)

np.empty(5)

np.eye(5)

np.arange(0, 10, 2)

np.linspace(0,1,5)

arr

arr.reshape(3,2)

